// Student Types
export const STUDENT_ADD_TOPIC = 'STUDENT_ADD_CONTACT';
export const STUDENT_DELETE_TOPIC = 'STUDENT_DELETE_CONTACT';
export const STUDENT_SET_CURRENT = 'STUDENT_SET_CURRENT'
export const STUDENT_CLEAR_CURRENT = 'STUDENT_CLEAR_CURRENT';
export const STUDENT_UPDATE_CONTACT = 'STUDENT_UPDATE_CONTACT';
export const STUDENT_FILTER_CONTACTS = 'STUDENT_FILTER_CONTACTS';
export const STUDENT_CLEAR_FILTER = 'STUDENT_CLEAR_FILTER';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// Teacher Types
export const TEACHER_ADD_TOPIC = 'TEACHER_ADD_CONTACT';
export const TEACHER_DELETE_TOPIC = 'TEACHER_DELETE_CONTACT';
export const TEACHER_SET_CURRENT = 'TEACHER_SET_CURRENT'
export const TEACHER_CLEAR_CURRENT = 'TEACHER_CLEAR_CURRENT';
export const TEACHER_UPDATE_TOPIC = 'TEACHER_UPDATE_CONTACT';
export const TEACHER_FILTER_TOPIC = 'TEACHER_FILTER_CONTACTS';
export const TEACHER_CLEAR_FILTER = 'TEACHER_CLEAR_FILTER';
export const TEACHER_SET_ALERT = 'TEACHER_SET_ALERT';
export const TEACHER_REMOVE_ALERT = 'TEACHER_REMOVE_ALERT';
// Auth Types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';